---
name: Integration Tests
on:
  pull_request:
    paths:
      - "action.yaml"
      - ".github/workflows/integration-tests.yaml"
  push:
    branches: ["main", "cv/push"]
    tags: ["*"]
    paths:
      - "action.yaml"
      - ".github/workflows/integration-tests.yaml"

jobs:
  target-unnamed:
    permissions: {}
    runs-on: ubuntu-latest
    steps:
      - run: sleep 10

  target-named:
    name: Target Named
    permissions: {}
    runs-on: ubuntu-latest
    steps:
      - run: sleep 10

  test-same-workflow:
    name: Test Same Workflow
    # These permissions are needed to:
    # - Checkout the repo
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        id: wait-for-job-unnamed
        with:
          run-id: ${{ github.run_id }}
          job-name: target-unnamed
          poll-interval: 5
      - name: Validate wait for unnamed job
        run: |
          set -x
          [[ "$conclusion" == "success" ]] || exit 1

          # https://docs.github.com/en/rest/actions/workflow-jobs?apiVersion=2022-11-28#get-a-job-for-a-workflow-run
          job_status="$(gh api -X GET "/repos/{owner}/{repo}/actions/jobs/${job_id:?}" --jq '.status')"
          [[ "$job_status" == "completed" ]] || exit 1
        env:
          GH_TOKEN: ${{ github.token }}
          job_id: ${{ steps.wait-for-job-unnamed.outputs.job-id }}
          conclusion: ${{ steps.wait-for-job-unnamed.outputs.conclusion }}
      - uses: ./
        id: wait-for-job-named
        with:
          run-id: ${{ github.run_id }}
          job-name: Target Named
          poll-interval: 5
      - name: Validate wait for named job
        run: |
          set -x
          [[ "$conclusion" == "success" ]] || exit 1

          # https://docs.github.com/en/rest/actions/workflow-jobs?apiVersion=2022-11-28#get-a-job-for-a-workflow-run
          job_status="$(gh api -X GET "/repos/{owner}/{repo}/actions/jobs/${job_id:?}" --jq '.status')"
          [[ "$job_status" == "completed" ]] || exit 1
        env:
          GH_TOKEN: ${{ github.token }}
          job_id: ${{ steps.wait-for-job-named.outputs.job-id }}
          conclusion: ${{ steps.wait-for-job-named.outputs.conclusion }}

  setup-build-workflow:
    name: Setup Build Workflow
    # These permissions are needed to:
    # - Create a workflow dispatch event: https://docs.github.com/en/rest/actions/workflows?apiVersion=2022-11-28#create-a-workflow-dispatch-event
    permissions: 
      actions: write
    runs-on: ubuntu-latest
    steps:
      - name: Initiate target workflow
        uses: benc-uk/workflow-dispatch@e2e5e9a103e331dad343f381a29e654aea3cf8fc # v1.2.4
        with:
          workflow: target-workflow.yaml
          ref: ${{ github.head_ref || github.ref_name }}  # Workflow dispatch only works on branches or tags

  test-build-workflow:
    name: Test Build Workflow
    needs: setup-build-workflow
    # These permissions are needed to:
    # - Checkout the repo
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: beacon-biosignals/get-workflow-run@v1
        id: workflow-run
        with:
          workflow-file: target-workflow.yaml
          commit-sha: ${{ github.event.pull_request.head.sha || github.sha }}
      - uses: ./
        id: wait-for-job
        with:
          run-id: ${{ steps.workflow-run.outputs.run-id }}
          job-name: Build
          poll-interval: 5
      - name: Validate wait job
        run: |
          [[ "$conclusion" == "success" ]] || exit 1

          # https://docs.github.com/en/rest/actions/workflow-jobs?apiVersion=2022-11-28#list-jobs-for-a-workflow-run
          run_jobs="$(gh api -X GET "/repos/{owner}/{repo}/actions/runs/${run_id:?}/jobs" --jq '.jobs | {jobs: map({name, status, conclusion})}')"

          # https://docs.github.com/en/rest/actions/workflow-jobs?apiVersion=2022-11-28#get-a-job-for-a-workflow-run
          job_status="$(gh api -X GET "/repos/{owner}/{repo}/actions/jobs/${job_id:?}" --jq '.status')"
          if [[ "$job_status" != "completed" ]]; then
              jq <<<"$run_jobs"
              exit 1
          fi

          # The workflow run status may be "queued" when a subset of the jobs have
          # completed and the remaining jobs are "queued".
          # https://docs.github.com/en/rest/actions/workflow-runs?apiVersion=2022-11-28#get-a-workflow-run
          run_status="$(gh api "/repos/{owner}/{repo}/actions/runs/${run_id}" --jq '.status')"
          if [[ "$run_status" != "in_progress" && "$run_status" != "queued" ]]; then
              jq <<<"$run_jobs"
              exit 1
          fi
        env:
          GH_TOKEN: ${{ github.token }}
          run_id: ${{ steps.workflow-run.outputs.run-id }}
          job_id: ${{ steps.wait-for-job.outputs.job-id }}
          conclusion: ${{ steps.wait-for-job.outputs.conclusion }}
      - uses: actions/download-artifact@v4
        with:
          name: build
          run-id: ${{ steps.workflow-run.outputs.run-id }}
          github-token: ${{ github.token }}
      - name: Validate artifact
        run: |
          jq <build.json
          [[ "$(jq -er .run_id <build.json)" == "${{ steps.workflow-run.outputs.run-id }}" ]] || exit 1
          [[ "$(jq -er .run_attempt <build.json)" == "${{ steps.workflow-run.outputs.run-attempt }}" ]] || exit 1

  test-missing-workflow:
    name: Test Missing Workflow
    # These permissions are needed to:
    # - Checkout the repo
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        id: wait-for-job
        with:
          run-id: ${{ github.run_id }}
          job-name: missing
          timeout: 10
          poll-interval: 5
        continue-on-error: true
      - name: Validate timeout
        run: |
          [[ "$outcome" == "failure" ]] || exit 1
          [[ -z "$job_id" ]] || exit 1
          [[ -z "$conclusion" ]] || exit 1
        env:
          outcome: ${{ steps.wait-for-job.outcome }}
          job_id: ${{ steps.wait-for-job.outputs.job-id }}
          conclusion: ${{ steps.wait-for-job.outputs.conclusion }}
